## Индивидуальное задание.
Элемент матрицы называется локальным минимумом, если он строго меньше всех
имеющихся у него соседей. 
- Подсчитать количество локальных минимумов заданной матрицы размером 10 на 10. 
- Найти сумму модулей элементов, расположенных выше главной диагонали.

In [17]:
import numpy as np

Создаем квадратную матрицу, размерностью 10 на 10

In [18]:
array = np.random.randint(-10, 10,(10, 10))
array

array([[ -6,   6,   7,  -3,   9,   1,  -1,   9,  -6,   7],
       [ -5,  -3,   8,  -6,   7,  -1,   9,   1,   9,  -3],
       [ -7,  -3,   2,   8,   9,  -5,   3,  -9,  -4,  -9],
       [ -5,  -6,   1,   3, -10,  -2,  -5,  -1,   6,   3],
       [  5,   7,  -1,   2,  -5,  -2,  -1,   9,   3, -10],
       [  7,   0,   7,   3,  -1,  -4,   8,   0, -10,   5],
       [  3,   6,  -5,   9,   2,  -5,  -4,  -3,   6,   3],
       [ -3,  -3,   9, -10,   6,   2,  -7,  -8,  -1,   4],
       [ -7,   6,   1,  -7,  -8,  -3,   4,   1,   0,   5],
       [ -9,  -8,   7,   8,   3,  -8,   3,   7,   0,  -8]])

##### Подсчитать количество локальных минимумов заданной матрицы размером 10 на 10

Используем функцию для поиска локальных минимумов

In [19]:
def local_minima(array_m):
    return ((array_m < np.roll(array_m,  1, 0)) &
            (array_m < np.roll(array_m, -1, 0)) &
            (array_m < np.roll(array_m,  1, 1)) &
            (array_m < np.roll(array_m, -1, 1)))

b = local_minima(array)
print(b)

[[False False False False False False  True False  True False]
 [False False False  True False False False False False False]
 [False False False False False  True False  True False  True]
 [False  True False False  True False  True False False False]
 [False False  True False False False False False False  True]
 [False  True False False False False False False  True False]
 [False False  True False False  True False False False False]
 [False False False  True False False False  True False False]
 [False False False False  True False False False False False]
 [ True False False False False  True False False False False]]


Считаем количество локальных минимумов

In [20]:
count = np.where((b == True), 1, 0).sum()
print(count)

20


##### Найти сумму модулей элементов, расположенных выше главной диагонали.

Находим модули элементов матрицы

In [21]:
modul = np.absolute(array)
print(modul)

[[ 6  6  7  3  9  1  1  9  6  7]
 [ 5  3  8  6  7  1  9  1  9  3]
 [ 7  3  2  8  9  5  3  9  4  9]
 [ 5  6  1  3 10  2  5  1  6  3]
 [ 5  7  1  2  5  2  1  9  3 10]
 [ 7  0  7  3  1  4  8  0 10  5]
 [ 3  6  5  9  2  5  4  3  6  3]
 [ 3  3  9 10  6  2  7  8  1  4]
 [ 7  6  1  7  8  3  4  1  0  5]
 [ 9  8  7  8  3  8  3  7  0  8]]


Находим сумму элементов, расположенных выше главной диагонали, при помощи функции trace(), которая позволяет получить сумму по главной диагонали со смещением offset

In [22]:
summa = sum([modul.trace(offset=i) for i in range(0,11)])
summa

280